language: cpp
os:
  - osx
  - linux
compiler:
  - gcc
  - clang
before_install:
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew update'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew upgrade cmake'
script: cmake --version && cmake . && make && make install
dist: trusty
sudo: false
addons:
  apt:
    packages:
    - cmake
cache:
  directories:
    - /usr/local/Homebrew
