language: cpp
os:
  - osx
  - linux
compiler:
  - gcc
  - clang
script:
  - cmake --version && pkg-config --version
  - cmake . && make && make test && sudo make install
  - cd $TRAVIS_BUILD_DIR/examples/makefile && make
  - cd $TRAVIS_BUILD_DIR/examples/cmake && PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig cmake . && make
dist: xenial
addons:
  apt:
    packages:
    - cmake
cache:
  directories:
    - /usr/local/Homebrew
