language: cpp
os:
  - osx
  - linux
compiler:
  - gcc
  - clang
before_install:
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew update'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew upgrade cmake'
script:
  - cmake --version && cmake . && make && sudo make install
  - cd examples/makefile && make
dist: xenial
addons:
  apt:
    packages:
    - cmake
cache:
  directories:
    - /usr/local/Homebrew
