language: cpp
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
before_install:
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew update'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew install cmake'
script: cmake . && make
dist: trusty
sudo: false
addons:
  apt:
    packages:
    - cmake