language: cpp
os:
  - osx
  - linux
  - windows
compiler:
  - gcc
  - clang
script:
  - cmake --version
  - cmake . && cmake --build . && make test && sudo make install
  - cd $TRAVIS_BUILD_DIR/examples/makefile && make
  - cd $TRAVIS_BUILD_DIR/examples/cmake && PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig cmake . && make
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew install meson'
  - cd $TRAVIS_BUILD_DIR/examples/meson && mkdir -p build && PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig meson build && ninja -v -C build
dist: xenial
addons:
  apt:
    packages:
    - cmake
    - meson
cache:
  directories:
    - /usr/local/Homebrew
